name: Keep Render Awake

on:
  workflow_dispatch:

  push:

  schedule:
    - cron: "* * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render API
        run: |
          curl https://gnn-api-t7k7.onrender.com/
